In [1]:
import numpy as np
import matplotlib.pyplot as plt
import fitsio
from fitsio import FITS,FITSHDR
from astropy import units as u
from astropy.coordinates import SkyCoord
from scipy import stats
from astropy.table import Table, Column
import matplotlib.colors as clr
import statsmodels.api as sm
import itertools as it
import pandas as pd
from io import StringIO 
from astropy.io import ascii
import math
import random
from scipy.interpolate import griddata
from sklearn import neighbors
import matplotlib.lines as mlines
import scipy
from scipy.stats import kde
from scipy.ndimage import gaussian_filter
from matplotlib.path import Path
import os
from gala.coordinates import MagellanicStreamNidever08
import matplotlib.image as mpimg
from scipy.spatial import ConvexHull, convex_hull_plot_2d
import matplotlib.ticker as ticker
from matplotlib.ticker import (MultipleLocator, FormatStrFormatter,
                               AutoMinorLocator)

In /Users/amyel/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/amyel/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/amyel/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /Users/amyel/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/amyel/anaconda3/lib/python3.7/site-packages/matplo

In [2]:
tiles={}

In [3]:
for filename in os.listdir('/Users/amyel/research/vmc/allfits/'):
    
    print(filename)
    
    fx = fitsio.FITS('/Users/amyel/research/vmc/allfits/'+filename)

    if filename[3] == '_':
        print(filename[:3])
        tiles[filename[:3]]=fx[1].read()
    else:
        print(filename[:4])
        tiles[filename[:4]]=fx[1].read()

9_8_data.fits
9_8
4_7_data.fits
4_7
2_6_data.fits
2_6
6_4_data.fits
6_4
9_5_data.fits
9_5
3_2_data.fits
3_2
5_3_data.fits
5_3
6_9_data.fits
6_9
8_7_data.fits
8_7
6_2_data.fits
6_2
5_8_data.fits
5_8
5_5_data.fits
5_5
9_3_data.fits
9_3
3_4_data.fits
3_4
7_6_data.fits
7_6
6_10data.fits
6_10
4_6_data.fits
4_6
9_9_data.fits
9_9
6_5_data.fits
6_5
2_7_data.fits
2_7
7_1_data.fits
7_1
9_4_data.fits
9_4
3_3_data.fits
3_3
5_2_data.fits
5_2
6_8_data.fits
6_8
6_3_data.fits
6_3
5_9_data.fits
5_9
8_6_data.fits
8_6
10_7data.fits
10_7
10_6data.fits
10_6
3_8_data.fits
3_8
5_4_data.fits
5_4
7_7_data.fits
7_7
3_5_data.fits
3_5
2_4_data.fits
2_4
8_3_data.fits
8_3
6_6_data.fits
6_6
4_5_data.fits
4_5
5_1_data.fits
5_1
9_7_data.fits
9_7
4_8_data.fits
4_8
7_2_data.fits
7_2
7_9_data.fits
7_9
4_3_data.fits
4_3
8_5_data.fits
8_5
3_6_data.fits
3_6
7_4_data.fits
7_4
8_8_data.fits
8_8
5_7_data.fits
5_7
6_7_data.fits
6_7
2_5_data.fits
2_5
8_2_data.fits
8_2
4_4_data.fits
4_4
10_4data.fits
10_4
10_5data.fits
10_5
4_9_d

In [4]:
names = list(tiles['6_5'].dtype.names)

In [5]:
names

['J_MAG',
 'J_ERR',
 'Ks_MAG',
 'Ks_ERR',
 'AVERAGE_RA',
 'AVERAGE_DEC',
 'Lcomp_J',
 'Lcomp_Ks',
 'J_SHARP',
 'Ks_SHARP',
 'syserr_J',
 'syserr_Ks',
 'Star_prob',
 'RA_Y',
 'DEC_Y',
 'Y_MAG',
 'Y_ERR',
 'Y_SHARP',
 'RA_J',
 'DEC_J',
 'RA_Ks',
 'DEC_Ks',
 'Lcomp_Y',
 'syserr_Y',
 'nY,nJ,nKs']

In [6]:
alll = {}

for name in names:
    alll[name]=np.array([])

In [7]:
for key in tiles.keys():
    print(key)
    for name in names:
        
        alll[name] = np.concatenate((alll[name],tiles[key][name]))

9_8
4_7
2_6
6_4
9_5
3_2
5_3
6_9
8_7
6_2
5_8
5_5
9_3
3_4
7_6
6_10
4_6
9_9
6_5
2_7
7_1
9_4
3_3
5_2
6_8
6_3
5_9
8_6
10_7
10_6
3_8
5_4
7_7
3_5
2_4
8_3
6_6
4_5
5_1
9_7
4_8
7_2
7_9
4_3
8_5
3_6
7_4
8_8
5_7
6_7
2_5
8_2
4_4
10_4
10_5
4_9
7_3
9_6
7_8
4_2
6_1
2_3
8_4
7_5
3_7
5_6
7_10
8_9


In [8]:
alll.keys()

dict_keys(['J_MAG', 'J_ERR', 'Ks_MAG', 'Ks_ERR', 'AVERAGE_RA', 'AVERAGE_DEC', 'Lcomp_J', 'Lcomp_Ks', 'J_SHARP', 'Ks_SHARP', 'syserr_J', 'syserr_Ks', 'Star_prob', 'RA_Y', 'DEC_Y', 'Y_MAG', 'Y_ERR', 'Y_SHARP', 'RA_J', 'DEC_J', 'RA_Ks', 'DEC_Ks', 'Lcomp_Y', 'syserr_Y', 'nY,nJ,nKs'])

In [9]:
array_list = [alll[name] for name in names]

In [10]:
array_list

[array([ 21.929,  21.975, -99.999, ...,  20.138,  21.927,  22.568]),
 array([ 1.1000e-01,  1.3600e-01, -9.9999e+01, ...,  2.2000e-02,
         9.2000e-02,  3.6200e-01]),
 array([ 21.871, -99.999, -99.999, ...,  19.978,  21.323, -99.999]),
 array([ 3.9300e-01, -9.9999e+01, -9.9999e+01, ...,  5.9000e-02,
         3.1400e-01, -9.9999e+01]),
 array([88.20005035, 90.82675934, 88.64665985, ..., 91.93366242,
        92.2492981 , 91.1542511 ]),
 array([-64.68087769, -64.68087769, -64.68087006, ..., -66.11746979,
        -66.11746979, -66.11746979]),
 array([0.660714, 0.720247, 0.      , ..., 0.915758, 0.728611, 0.380719]),
 array([0.154766, 0.      , 0.      , ..., 0.907895, 0.338776, 0.      ]),
 array([ 2.8200e-01, -1.6610e+00, -9.9999e+01, ...,  3.5900e-01,
         4.2000e-02, -7.9610e+00]),
 array([ -2.91 , -99.999, -99.999, ...,   0.131,  -1.713, -99.999]),
 array([ 0.011909,  0.009388,  0.      , ..., -0.005381,  0.011333,
         0.006167]),
 array([-0.102998,  0.      ,  0.      , ..

In [11]:
fitsio.write('/Users/amyel/research/vmc/files/all_psf.fits',array_list,names=names)